"""Tests for the C4 view generator (STO-101).

Emission is asserted against committed golden files rather than regexes: a
golden file is what makes a layout change visible in review.
"""
import json
import os
import shutil

import pytest

import generate_c4 as g4
import validate_design as vd

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures", "c4")


def case(name):
    root = os.path.join(FIXTURES, name)
    return (
        os.path.join(root, "design"),
        os.path.join(root, "model.json"),
        os.path.join(root, "expected"),
    )


def load_model(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def test_edges_resolve_through_the_provider():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.edges() == [
        ("CMP-001", "CMP-002", "IF-001"),
        ("CMP-001", "CMP-003", "IF-002"),
    ]


def test_asrs_are_read_from_drivers():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.asrs == ["FR-001", "NFR-001"]


def test_alias_rule_is_reversible():
    assert g4.alias_for("CMP-001", "internal") == "cmp_001"
    assert g4.alias_for("CMP-010", "external") == "ext_cmp_010"
    assert g4.alias_for("CMP-AUTH-004", "internal") == "cmp_auth_004"


def test_model_missing_a_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"] = ["CMP-001"]
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e for e in errors)


def test_model_placing_a_component_twice_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "key": "second", "name": "Second", "technology": "Python",
        "description": "…", "components": ["CMP-002"],
    })
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e and "two" in e.lower() for e in errors)


def test_model_placing_an_external_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"].append("CMP-003")
    errors = g4.validate_model(model, dset)
    assert any("CMP-003" in e for e in errors)


def test_context_view_matches_golden(tmp_path):
    design_dir, model_path, expected = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    written = (out / "diagrams" / "DIA-001-system-context.md").read_text()
    golden = open(os.path.join(expected, "DIA-001-system-context.md")).read()
    assert written == golden


def test_generation_is_deterministic(tmp_path):
    design_dir, model_path, _ = case("single-container")
    runs = []
    for i in range(2):
        out = tmp_path / f"run{i}"
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        runs.append((out / "diagrams" / "DIA-001-system-context.md").read_text())
    assert runs[0] == runs[1]


def test_generated_view_passes_the_validator(tmp_path):
    """Round-trip: what this tool writes must be accepted by
    validate_design.py itself, not merely by this test's own golden-file
    comparison — a golden file generated by buggy emission code would still
    match itself. This is the check that catches an unquoted YAML scalar
    (e.g. a description containing a colon) breaking frontmatter parsing."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_generated_title_and_description_parse_identically_both_ways(
    tmp_path, monkeypatch
):
    """The invariant that actually matters is not "the validator exits 0" --
    it's "pyyaml and the stdlib fallback read the same value back". An
    exit-code check can't tell the two apart: the stdlib fallback's
    `text.partition(":")` only splits on the FIRST colon, so an unquoted
    value with a LATER colon (this generator's own Context description)
    survives intact rather than raising or truncating, and a validator
    round-trip alone would pass even with the pre-fix unquoted emission.
    Only comparing the two parsers' parsed values catches that quietly."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    diagram_path = str(out / "diagrams" / "DIA-001-system-context.md")

    assert g4.core.HAVE_YAML, "pyyaml must be installed to exercise both paths"
    pyyaml_data, err = g4.parse_frontmatter(diagram_path)
    assert err is None, err

    monkeypatch.setattr(g4.core, "HAVE_YAML", False)
    stdlib_data, err = g4.parse_frontmatter(diagram_path)
    assert err is None, err

    assert pyyaml_data["title"] == stdlib_data["title"] == "System Context"
    intended_description = (
        "System context for Order System: its actors, its boundary, and "
        "the external systems it depends on."
    )
    assert pyyaml_data["description"] == intended_description
    assert stdlib_data["description"] == intended_description


def test_yaml_q_agrees_across_parsers_on_hostile_characters(tmp_path, monkeypatch):
    """A title or description a human wrote freely can contain a colon, a
    quote, a hashtag preceded by a space, a backslash, a stray carriage
    return, and a raw control character — all bytes an ordinary prose
    editor will happily save. yaml_q must sanitize every one of them to
    bytes both parsers read back the same way, not merely bytes that happen
    not to crash pyyaml.

    ``" #"`` (space then hash) is included and IS preceded by a space this
    time: `_strip_inline_comment` in lib/artifact_core.py truncates a value
    at a literal " #" regardless of quoting, so an unfolded one is read
    differently by the two parsers — the exact divergence sanitize-not-
    escape exists to prevent. `\\r`, `\\x0b` (a C0 control) and `\\x7f`
    (DEL) are included because the stdlib fallback's frontmatter parser
    splits the block on ``str.splitlines()``, which treats all three as a
    line break — any one surviving into a value would silently split a
    single field into two rows."""
    raw = 'Report #42: uses C:\\Users\\x and a "quoted" phrase\r\x0b\x7f'
    quoted = g4.yaml_q(raw)
    assert "\\" not in quoted, "no backslash may survive into the YAML text"
    assert quoted.count('"') == 2, "only the wrapping pair of quotes"
    assert " #" not in quoted, (
        "a literal space-hash reads as a comment introducer to the stdlib fallback"
    )
    for hostile in ("\r", "\x0b", "\x7f"):
        assert hostile not in quoted, f"{hostile!r} must not survive into the YAML text"

    out_dir = tmp_path / "diagrams"
    path = g4.write_diagram(
        str(out_dir), dia_id="DIA-999", title=raw, level="context",
        container=None, description=raw, traces_from=[], confidence="high",
        created_at="2026-08-22", block="C4Context",
    )

    assert g4.core.HAVE_YAML, "pyyaml must be installed to exercise both paths"
    pyyaml_data, err = g4.parse_frontmatter(path)
    assert err is None, err

    monkeypatch.setattr(g4.core, "HAVE_YAML", False)
    stdlib_data, err = g4.parse_frontmatter(path)
    assert err is None, err

    assert pyyaml_data["title"] == stdlib_data["title"]
    assert pyyaml_data["description"] == stdlib_data["description"]
    assert pyyaml_data["title"] == "Report 42: uses C:/Users/x and a 'quoted' phrase"


def test_model_actor_entrypoint_naming_unknown_container_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["actors"][0]["entrypoint"] = "does-not-exist"
    errors = g4.validate_model(model, dset)
    assert any("does-not-exist" in e for e in errors)


def test_container_view_matches_golden(tmp_path):
    for name in ("single-container", "multi-container"):
        design_dir, model_path, expected = case(name)
        out = tmp_path / name
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        written = (out / "diagrams" / "DIA-002-container-view.md").read_text()
        golden = open(os.path.join(expected, "DIA-002-container-view.md")).read()
        assert written == golden, name


def test_intra_container_edges_are_not_container_level(tmp_path):
    """CMP-001 -> IF-001 -> CMP-002 lives entirely inside `app`; drawing it
    between containers would assert a boundary crossing that does not exist."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-002-container-view.md").read_text()
    assert "IF-001" not in body
    assert "IF-002" in body  # app -> the external gateway still crosses


def test_cross_container_edge_is_drawn(tmp_path):
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-002-container-view.md").read_text()
    assert "Rel(ctr_worker, ctr_app," in body
    assert "IF-001" in body


def test_model_container_without_a_key_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "name": "Nameless", "technology": "Python",
        "description": "…", "components": [],
    })
    errors = g4.validate_model(model, dset)
    assert any("no 'key'" in e for e in errors)


def test_model_duplicate_container_keys_are_rejected():
    """Two containers keyed `app` would otherwise emit a Container view
    declaring `ctr_app` twice with contradicting labels, and two component
    views both claiming `container: app` — both structural gates were
    passing over that before this check existed."""
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "key": model["containers"][0]["key"], "name": "Duplicate",
        "technology": "Python", "description": "…", "components": [],
    })
    errors = g4.validate_model(model, dset)
    assert any("used by more than one container" in e for e in errors)


def test_model_container_with_no_components_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "key": "empty", "name": "Empty", "technology": "Python",
        "description": "…", "components": [],
    })
    errors = g4.validate_model(model, dset)
    assert any("empty 'components' list" in e for e in errors)


def test_component_views_match_golden(tmp_path):
    for name, files in (
        ("single-container", ["DIA-003-component-view-order-app.md"]),
        ("multi-container", ["DIA-003-component-view-order-app.md",
                             "DIA-004-component-view-worker.md"]),
    ):
        design_dir, model_path, expected = case(name)
        out = tmp_path / name
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        for filename in files:
            written = (out / "diagrams" / filename).read_text()
            golden = open(os.path.join(expected, filename)).read()
            assert written == golden, filename


def test_cross_container_endpoint_renders_as_a_container(tmp_path):
    """The worker's edge lands on a component in another container. Drawing
    that component here would place it in two component views at once, which
    validate_design.py rejects — so it renders as the container instead."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-004-component-view-worker.md").read_text()
    assert "Container(ctr_app," in body
    assert "Component(cmp_002," not in body


def test_back_fill_maps_components_to_the_view_they_appear_in(tmp_path, capsys):
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    summary = json.loads(capsys.readouterr().out)
    back_fill = summary["traces_to_diagrams"]
    assert back_fill["CMP-001"] == ["DIA-003"]
    assert back_fill["CMP-004"] == ["DIA-004"]
    # An external appears at context and container level, never in a component view.
    assert back_fill["CMP-003"] == ["DIA-001", "DIA-002"]


def test_generated_set_passes_the_structural_validator(tmp_path):
    """The gate this whole feature has to survive: everything the generator
    writes is a valid artifact, consistent with the set it was drawn from."""
    import validate_design as vd

    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_context_view_dedupes_when_several_internals_share_an_external_edge():
    """Found against the tamagotchi worked example (STO-101 Task 10): five
    internal components (CMP-001, CMP-003, CMP-004, CMP-007, CMP-009) all
    depend on IF-001, provided by the external System Clock. At context
    level every one of those collapses to the same fact -- "the system
    depends on the clock" -- but `render_context` had no dedup, unlike
    `render_container` and `render_component`, so it emitted the identical
    `Rel(sys, ext_cmp_011, ...)` line once per consumer. No shipped fixture
    had two internal components sharing one external interface, so nothing
    caught it until a real design set did. This pins the fix: one Rel per
    distinct (source, destination, interface) triple, however many internal
    components share it."""
    dset = g4.DesignSet(
        components={
            "CMP-001": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "A", "responsibility": "…"},
            "CMP-002": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "B", "responsibility": "…"},
            "CMP-003": {"boundary": "external", "depends_on": [],
                       "title": "Clock", "responsibility": "…"},
        },
        interfaces={
            "IF-001": {"provider": "CMP-003", "title": "Time Source"},
        },
        asrs=[],
    )
    model = {
        "system_name": "Sys",
        "system_description": "…",
        "actors": [],
        "containers": [{"key": "app", "name": "App", "technology": "…",
                        "description": "…",
                        "components": ["CMP-001", "CMP-002"]}],
    }
    block = g4.render_context(model, dset)
    assert block.count("Rel(sys, ext_cmp_003,") == 1


def test_container_view_dedupes_two_members_of_one_container_sharing_an_edge():
    """Container level collapses each component into its container, so two
    members of one container depending on the same interface become the
    same fact -- "this container depends on that one" -- and
    `render_container` dedupes on `(source, destination, interface)` to
    state it once.

    `render_context` and `render_component` each already pin their own
    collapse. `render_container`'s was pinned only indirectly, by the
    tamagotchi golden, where five internal components share IF-001; that
    made the guard's coverage a side effect of one worked example rather
    than a stated rule. Removing the `key in seen` guard must fail here."""
    dset = g4.DesignSet(
        components={
            "CMP-001": {"boundary": "internal", "depends_on": ["IF-001"],
                        "title": "Consumer One", "responsibility": "…"},
            "CMP-002": {"boundary": "internal", "depends_on": ["IF-001"],
                        "title": "Consumer Two", "responsibility": "…"},
            "CMP-003": {"boundary": "external", "depends_on": [],
                        "title": "Clock", "responsibility": "…"},
        },
        interfaces={
            "IF-001": {"provider": "CMP-003", "title": "Time Source"},
        },
        asrs=[],
    )
    model = {
        "system_name": "Sys",
        "system_description": "…",
        "actors": [],
        "containers": [{"key": "app", "name": "App", "technology": "…",
                        "description": "…",
                        "components": ["CMP-001", "CMP-002"]}],
    }
    block = g4.render_container(model, dset)
    assert block.count("Rel(ctr_app, ext_cmp_003,") == 1


def test_worked_example_generates_a_valid_diagram_set(tmp_path):
    """The shipped tamagotchi set as STO-219 regenerated it: 19 components
    (17 internal, 2 external) across TWO containers, so four views — one
    context, one container, and one component view per container. Pinned
    because it is the only real set this tool is exercised against.

    Asserts byte-identical output against the committed
    `docs/requirements/examples/tamagotchi/design/diagrams/` files, not just
    exit 0 and existence — an exit-0-and-exists check would stay green even
    if a Rel-dedup or self-edge guard were reverted and started emitting
    duplicate lines, since the file would still exist and still validate (a
    duplicate `Rel` line is not itself a schema or structural violation).

    What this pins changed with the regeneration. The pre-STO-219 set had
    five internal components sharing one external interface (the system
    clock), which made it an incidental witness for `render_context`'s and
    `render_container`'s Rel dedup. The regenerated set routes every
    platform edge through the single platform-adapter component NFR-006
    requires, so each external interface now has exactly one internal
    consumer and that shape is gone from here. It is not lost: both dedups
    are pinned directly by
    `test_context_view_dedupes_when_several_internals_share_an_external_edge`
    and `test_container_view_dedupes_two_members_of_one_container_sharing_an_edge`,
    which exist precisely so the guarantee is a stated rule rather than a
    side effect of one worked example. What this golden now uniquely covers
    is the multi-container projection over a real set: container-to-container
    edges across the webview/core seam, and per-container DIA- allocation in
    sorted key order."""
    import validate_design as vd

    repo_root = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
    example = os.path.join(repo_root, "docs", "requirements", "examples",
                           "tamagotchi", "design")
    out = tmp_path / "design"
    shutil.copytree(example, out)
    shutil.rmtree(out / "diagrams")
    model = os.path.join(FIXTURES, "tamagotchi-model.json")
    assert g4.main([str(out), "--model", model, "--created-at", "2026-08-24"]) == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0

    for name in ("DIA-001-system-context.md", "DIA-002-container-view.md",
                 "DIA-003-component-view-pet-core.md",
                 "DIA-004-component-view-pet-webview-ui.md"):
        written = (out / "diagrams" / name).read_text()
        golden = open(os.path.join(example, "diagrams", name)).read()
        assert written == golden, name


def test_container_order_in_the_model_does_not_affect_dia_numbering(tmp_path):
    """DIA- IDs are allocated in `sorted(containers, key=lambda c: c["key"])`
    order (generate_c4.py `generate()`), not in the model's array order —
    that sort is the "one DIA- per container in key order" determinism
    guarantee `agents/c4-generator.md`, the spec, and SKILL.md all state.
    Reversing the model's container array must not move which container
    gets which DIA- ID."""
    design_dir, model_path, _ = case("multi-container")
    model = load_model(model_path)
    model["containers"] = list(reversed(model["containers"]))
    reversed_model_path = os.path.join(str(tmp_path), "reversed-model.json")
    with open(reversed_model_path, "w", encoding="utf-8") as handle:
        json.dump(model, handle)

    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", reversed_model_path,
                    "--created-at", "2026-08-22"]) == 0
    assert (out / "diagrams" / "DIA-003-component-view-order-app.md").exists()
    assert (out / "diagrams" / "DIA-004-component-view-worker.md").exists()


def test_component_view_dedupes_two_members_of_another_container_sharing_one_if():
    """Rendering container A's component view: two DIFFERENT members of
    container B (CMP-002, CMP-003) both depend on IF-001, provided by
    CMP-001, a member of A. Both edges' non-member endpoint collapses to the
    same `container_alias("b")` (`endpoint()` in `render_component`), so
    without the `key in seen` dedup at `render_component:369` this emits two
    identical `Rel(ctr_b, cmp_001, ...)` lines instead of one — the same bug
    class Task 10 found and fixed in `render_context`."""
    dset = g4.DesignSet(
        components={
            "CMP-001": {"boundary": "internal", "depends_on": [],
                       "title": "Provider", "responsibility": "…"},
            "CMP-002": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "Consumer One", "responsibility": "…"},
            "CMP-003": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "Consumer Two", "responsibility": "…"},
        },
        interfaces={
            "IF-001": {"provider": "CMP-001", "title": "Shared Interface"},
        },
        asrs=[],
    )
    model = {
        "system_name": "Sys",
        "system_description": "…",
        "actors": [],
        "containers": [
            {"key": "a", "name": "A", "technology": "…", "description": "…",
             "components": ["CMP-001"]},
            {"key": "b", "name": "B", "technology": "…", "description": "…",
             "components": ["CMP-002", "CMP-003"]},
        ],
    }
    container_a = model["containers"][0]
    block = g4.render_component(model, dset, container_a)
    assert block.count("Rel(ctr_b, cmp_001,") == 1


def test_component_view_skips_a_self_referential_edge():
    """A component that both consumes and provides the same interface
    produces a `(consumer, provider)` pair that resolves to the same
    endpoint alias on both sides. `render_component:369`'s `key[0] ==
    key[1]` guard drops it rather than emitting a nonsensical
    `Rel(cmp_001, cmp_001, ...)` self-loop."""
    dset = g4.DesignSet(
        components={
            "CMP-001": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "Self", "responsibility": "…"},
        },
        interfaces={"IF-001": {"provider": "CMP-001", "title": "Loopback"}},
        asrs=[],
    )
    model = {
        "system_name": "Sys",
        "system_description": "…",
        "actors": [],
        "containers": [{"key": "a", "name": "A", "technology": "…",
                        "description": "…", "components": ["CMP-001"]}],
    }
    block = g4.render_component(model, dset, model["containers"][0])
    assert "Rel(cmp_001, cmp_001" not in block


def test_unbalanced_parens_in_prose_still_pass_the_validator(tmp_path):
    """A component's `responsibility` is free-form prose the model is not
    wrong to write with a lone, unmatched paren (`Owns the order lifecycle
    (submission to settlement.`) — no documented recovery fits, because the
    content is not a defect: re-dispatching c4-generator cannot help, and
    nothing forbids a lone paren in prose. `q()` strips parens from Mermaid
    label text so the emitted line stays balanced regardless of what the
    source prose did."""
    import validate_design as vd

    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    cmp_path = out / "components" / "CMP-001-order-service.md"
    original = "responsibility: Owns the order lifecycle from submission to settlement."
    unbalanced = "responsibility: Owns the order lifecycle (submission to settlement."
    text = cmp_path.read_text()
    assert original in text
    cmp_path.write_text(text.replace(original, unbalanced))

    assert g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"]) == 0
    body = (out / "diagrams" / "DIA-003-component-view-order-app.md").read_text()
    assert "lifecycle submission" in body, "'(' must be stripped, not balanced"
    for line in body.split("```mermaid")[1].splitlines():
        assert line.count("(") == line.count(")"), line
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_regeneration_removes_a_stale_diagram_file(tmp_path):
    """C1 regression: renaming a container's `name` (same `key`) changes the
    component view's filename — `write_diagram` slugs the diagram's
    `title`, and a component view's title embeds `container["name"]` — so
    regenerating over an existing set must delete the OLD filename, not
    just write the new one alongside it. Left stale, `DIA-004` is claimed
    by two files at once and `validate_design.py` fails with `duplicate id
    'DIA-004'` plus `CMP-004 appears in 2 component-level diagrams`."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    stale = out / "diagrams" / "DIA-004-component-view-worker.md"
    assert stale.exists()

    model = load_model(model_path)
    model["containers"][1]["name"] = "Notification Worker"
    assert model["containers"][1]["key"] == "worker"
    renamed_model_path = os.path.join(str(tmp_path), "renamed-model.json")
    with open(renamed_model_path, "w", encoding="utf-8") as handle:
        json.dump(model, handle)

    code = g4.main([str(out), "--model", renamed_model_path,
                    "--created-at", "2026-08-22"])
    assert code == 0

    renamed = out / "diagrams" / "DIA-004-component-view-notification-worker.md"
    assert renamed.exists()
    assert not stale.exists(), "the old DIA-004 filename must not survive regeneration"

    other_files = {p.name for p in (out / "diagrams").iterdir()}
    assert "DIA-004-component-view-worker.md" not in other_files

    import validate_design as vd
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_regeneration_reports_the_removed_stale_file_in_the_summary(tmp_path, capsys):
    """The JSON summary's `removed` list is how the formatter (and a human
    re-running the tool by hand) learns a rename actually cleaned up after
    itself, rather than silently deleting files with no record."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    capsys.readouterr()  # discard the first run's summary

    stale = out / "diagrams" / "DIA-004-component-view-worker.md"
    model = load_model(model_path)
    model["containers"][1]["name"] = "Notification Worker"
    renamed_model_path = os.path.join(str(tmp_path), "renamed-model.json")
    with open(renamed_model_path, "w", encoding="utf-8") as handle:
        json.dump(model, handle)

    assert g4.main([str(out), "--model", renamed_model_path,
                    "--created-at", "2026-08-22"]) == 0
    summary = json.loads(capsys.readouterr().out)
    assert summary["removed"] == [str(stale)]


def test_generate_does_not_touch_files_outside_the_diagrams_directory(tmp_path):
    """The stale-file guard is deliberately narrow: it must never reach for
    anything that is not a `DIA-*.md` file directly inside `out_dir`. A
    component file that happens to start with `DIA` in its title-derived
    slug, or a subdirectory, must survive a regeneration untouched."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0

    diagrams_dir = out / "diagrams"
    decoy_file = diagrams_dir / "DIA-NOTES.txt"
    decoy_file.write_text("not a diagram")
    decoy_dir = diagrams_dir / "DIA-999-subdir"
    decoy_dir.mkdir()
    (decoy_dir / "DIA-999-nested.md").write_text("nested, must not be touched")

    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    assert decoy_file.exists()
    assert decoy_dir.exists()
    assert (decoy_dir / "DIA-999-nested.md").exists()


def test_regeneration_never_deletes_a_file_this_run_just_wrote(tmp_path):
    """The guard's rule is "delete a `DIA-` file this run did not write",
    but `written_paths` holds the names the run chose while `os.listdir`
    reports the names the directory actually holds. Those two diverge on a
    case-insensitive filesystem: rename a diagram to
    `DIA-004-Component-View-Worker.md` on macOS and the next run's `open()`
    of the lower-cased name reopens that very file, while the directory
    still lists the old casing. Compared by spelling, that entry reads as
    stale and gets removed -- deleting the diagram the run had just
    written, and leaving a container with no component view.

    A case-insensitive directory cannot be created on this platform, so the
    second name here is a hard link: one inode, two directory entries --
    the same divergence between chosen name and listed name, reachable on
    Linux. What is pinned is that the guard compares file identity rather
    than spelling, so no name the just-written inode answers to is ever
    removed."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0

    written = out / "diagrams" / "DIA-004-component-view-worker.md"
    assert written.exists()
    other_name = out / "diagrams" / "DIA-004-Component-View-Worker.md"
    os.link(str(written), str(other_name))

    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    assert written.exists(), "the diagram this run wrote must survive"
    assert other_name.exists(), (
        "a second name for the just-written inode is that same file, "
        "not a stale leftover"
    )


def test_created_at_is_required_at_the_argparse_level(tmp_path):
    """A run missing `--created-at` must exit 2 (usage error), not fall
    through to `validate_model` and exit 1 — the two mean different things
    to the caller (agents/design-formatter.md re-dispatches a model failure
    to c4-generator; an environment/usage error is not that)."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    with pytest.raises(SystemExit) as excinfo:
        g4.main([str(out), "--model", model_path])
    assert excinfo.value.code == 2


def test_missing_asr_heading_warns_on_stderr(tmp_path, capsys):
    """A `drivers.md` with no `## Architecturally Significant Requirements`
    heading at all is indistinguishable, by return value, from a legal
    `drivers.md` whose ASR section exists but is empty ("None identified")
    — `_read_asrs` returns `[]` for both. Only the missing-heading case is a
    problem worth a human's attention: DIA-001 will silently ship with an
    empty `traces_from` because of a malformed file, not a genuine "no ASRs"
    answer. Distinguish them on stderr without changing either's return
    value or exit code."""
    design_dir, _, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    (out / "drivers.md").write_text("# Architecture Drivers\n\nNothing here.\n")

    capsys.readouterr()
    asrs = g4.DesignSet._read_asrs(str(out))
    captured = capsys.readouterr()
    assert asrs == []
    assert "drivers.md" in captured.err
    assert "Architecturally Significant Requirements" in captured.err


def test_missing_drivers_file_warns_on_stderr(tmp_path):
    """An unreadable/absent `drivers.md` is the same silent-empty-list
    failure mode as a missing heading, and gets the same stderr warning."""
    out = tmp_path / "design"
    out.mkdir()
    asrs = g4.DesignSet._read_asrs(str(out))
    assert asrs == []


def test_empty_asr_section_is_silent(tmp_path, capsys):
    """A `drivers.md` whose ASR heading is present but has no bullets under
    it ("None identified.") is a legal, honest answer — this must NOT warn,
    or every project with genuinely zero ASRs would get a spurious warning
    on every run."""
    out = tmp_path / "design"
    out.mkdir()
    (out / "drivers.md").write_text(
        "# Architecture Drivers\n\n"
        "## Architecturally Significant Requirements\n\n"
        "- None identified.\n\n"
        "## Tradeoffs\n\n- None identified.\n"
    )
    capsys.readouterr()
    asrs = g4.DesignSet._read_asrs(str(out))
    captured = capsys.readouterr()
    assert asrs == []
    assert captured.err == ""
