"""Tests for the C4 view generator (STO-101).

Emission is asserted against committed golden files rather than regexes: a
golden file is what makes a layout change visible in review.
"""
import json
import os
import shutil

import pytest

import generate_c4 as g4
import validate_design as vd

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures", "c4")


def case(name):
    root = os.path.join(FIXTURES, name)
    return (
        os.path.join(root, "design"),
        os.path.join(root, "model.json"),
        os.path.join(root, "expected"),
    )


def load_model(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def test_edges_resolve_through_the_provider():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.edges() == [
        ("CMP-001", "CMP-002", "IF-001"),
        ("CMP-001", "CMP-003", "IF-002"),
    ]


def test_asrs_are_read_from_drivers():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.asrs == ["FR-001", "NFR-001"]


def test_alias_rule_is_reversible():
    assert g4.alias_for("CMP-001", "internal") == "cmp_001"
    assert g4.alias_for("CMP-010", "external") == "ext_cmp_010"
    assert g4.alias_for("CMP-AUTH-004", "internal") == "cmp_auth_004"


def test_model_missing_a_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"] = ["CMP-001"]
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e for e in errors)


def test_model_placing_a_component_twice_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "key": "second", "name": "Second", "technology": "Python",
        "description": "…", "components": ["CMP-002"],
    })
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e and "two" in e.lower() for e in errors)


def test_model_placing_an_external_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"].append("CMP-003")
    errors = g4.validate_model(model, dset)
    assert any("CMP-003" in e for e in errors)


def test_context_view_matches_golden(tmp_path):
    design_dir, model_path, expected = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    written = (out / "diagrams" / "DIA-001-system-context.md").read_text()
    golden = open(os.path.join(expected, "DIA-001-system-context.md")).read()
    assert written == golden


def test_generation_is_deterministic(tmp_path):
    design_dir, model_path, _ = case("single-container")
    runs = []
    for i in range(2):
        out = tmp_path / f"run{i}"
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        runs.append((out / "diagrams" / "DIA-001-system-context.md").read_text())
    assert runs[0] == runs[1]


def test_generated_view_passes_the_validator(tmp_path):
    """Round-trip: what this tool writes must be accepted by
    validate_design.py itself, not merely by this test's own golden-file
    comparison — a golden file generated by buggy emission code would still
    match itself. This is the check that catches an unquoted YAML scalar
    (e.g. a description containing a colon) breaking frontmatter parsing."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_generated_view_passes_the_validator_in_fallback_mode(
    tmp_path, monkeypatch
):
    """Same round-trip, forced onto the stdlib fallback parser (no pyyaml,
    no jsonschema). The sanitize-then-quote fix has to satisfy both parse
    paths identically, or a machine without the optional deps silently
    diverges from CI. Mirrors test_validate_design.py's
    test_valid_set_passes_in_fallback_mode."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    monkeypatch.setattr(vd.core, "HAVE_YAML", False)
    monkeypatch.setattr(vd.core, "HAVE_JSONSCHEMA", False)
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_model_actor_entrypoint_naming_unknown_container_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["actors"][0]["entrypoint"] = "does-not-exist"
    errors = g4.validate_model(model, dset)
    assert any("does-not-exist" in e for e in errors)


def test_model_container_without_a_key_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "name": "Nameless", "technology": "Python",
        "description": "…", "components": [],
    })
    errors = g4.validate_model(model, dset)
    assert any("no 'key'" in e for e in errors)
