"""Tests for the C4 view generator (STO-101).

Emission is asserted against committed golden files rather than regexes: a
golden file is what makes a layout change visible in review.
"""
import json
import os
import shutil

import pytest

import generate_c4 as g4
import validate_design as vd

HERE = os.path.dirname(os.path.abspath(__file__))
FIXTURES = os.path.join(HERE, "fixtures", "c4")


def case(name):
    root = os.path.join(FIXTURES, name)
    return (
        os.path.join(root, "design"),
        os.path.join(root, "model.json"),
        os.path.join(root, "expected"),
    )


def load_model(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def test_edges_resolve_through_the_provider():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.edges() == [
        ("CMP-001", "CMP-002", "IF-001"),
        ("CMP-001", "CMP-003", "IF-002"),
    ]


def test_asrs_are_read_from_drivers():
    design_dir, _, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    assert dset.asrs == ["FR-001", "NFR-001"]


def test_alias_rule_is_reversible():
    assert g4.alias_for("CMP-001", "internal") == "cmp_001"
    assert g4.alias_for("CMP-010", "external") == "ext_cmp_010"
    assert g4.alias_for("CMP-AUTH-004", "internal") == "cmp_auth_004"


def test_model_missing_a_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"] = ["CMP-001"]
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e for e in errors)


def test_model_placing_a_component_twice_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "key": "second", "name": "Second", "technology": "Python",
        "description": "…", "components": ["CMP-002"],
    })
    errors = g4.validate_model(model, dset)
    assert any("CMP-002" in e and "two" in e.lower() for e in errors)


def test_model_placing_an_external_component_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"][0]["components"].append("CMP-003")
    errors = g4.validate_model(model, dset)
    assert any("CMP-003" in e for e in errors)


def test_context_view_matches_golden(tmp_path):
    design_dir, model_path, expected = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    written = (out / "diagrams" / "DIA-001-system-context.md").read_text()
    golden = open(os.path.join(expected, "DIA-001-system-context.md")).read()
    assert written == golden


def test_generation_is_deterministic(tmp_path):
    design_dir, model_path, _ = case("single-container")
    runs = []
    for i in range(2):
        out = tmp_path / f"run{i}"
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        runs.append((out / "diagrams" / "DIA-001-system-context.md").read_text())
    assert runs[0] == runs[1]


def test_generated_view_passes_the_validator(tmp_path):
    """Round-trip: what this tool writes must be accepted by
    validate_design.py itself, not merely by this test's own golden-file
    comparison — a golden file generated by buggy emission code would still
    match itself. This is the check that catches an unquoted YAML scalar
    (e.g. a description containing a colon) breaking frontmatter parsing."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_generated_title_and_description_parse_identically_both_ways(
    tmp_path, monkeypatch
):
    """The invariant that actually matters is not "the validator exits 0" --
    it's "pyyaml and the stdlib fallback read the same value back". An
    exit-code check can't tell the two apart: the stdlib fallback's
    `text.partition(":")` only splits on the FIRST colon, so an unquoted
    value with a LATER colon (this generator's own Context description)
    survives intact rather than raising or truncating, and a validator
    round-trip alone would pass even with the pre-fix unquoted emission.
    Only comparing the two parsers' parsed values catches that quietly."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    code = g4.main([
        str(out), "--model", model_path, "--created-at", "2026-08-22",
    ])
    assert code == 0
    diagram_path = str(out / "diagrams" / "DIA-001-system-context.md")

    assert g4.core.HAVE_YAML, "pyyaml must be installed to exercise both paths"
    pyyaml_data, err = g4.parse_frontmatter(diagram_path)
    assert err is None, err

    monkeypatch.setattr(g4.core, "HAVE_YAML", False)
    stdlib_data, err = g4.parse_frontmatter(diagram_path)
    assert err is None, err

    assert pyyaml_data["title"] == stdlib_data["title"] == "System Context"
    intended_description = (
        "System context for Order System: its actors, its boundary, and "
        "the external systems it depends on."
    )
    assert pyyaml_data["description"] == intended_description
    assert stdlib_data["description"] == intended_description


def test_yaml_q_agrees_across_parsers_on_hostile_characters(tmp_path, monkeypatch):
    """A title or description a human wrote freely can contain a colon, a
    quote, a hashtag, and — a Windows path is not exotic — a backslash.
    yaml_q must sanitize all of them to bytes both parsers read back the
    same way, not merely bytes that happen not to crash pyyaml. (A hash is
    included here but NOT preceded by a space: `_strip_inline_comment` in
    lib/artifact_core.py truncates on a literal " #" regardless of quoting,
    which is a pre-existing stdlib-fallback limitation this test does not
    exercise or attempt to fix.)"""
    raw = 'Report#42: uses C:\\Users\\x and a "quoted" phrase'
    quoted = g4.yaml_q(raw)
    assert "\\" not in quoted, "no backslash may survive into the YAML text"
    assert quoted.count('"') == 2, "only the wrapping pair of quotes"

    out_dir = tmp_path / "diagrams"
    path = g4.write_diagram(
        str(out_dir), dia_id="DIA-999", title=raw, level="context",
        container=None, description=raw, traces_from=[], confidence="high",
        created_at="2026-08-22", block="C4Context",
    )

    assert g4.core.HAVE_YAML, "pyyaml must be installed to exercise both paths"
    pyyaml_data, err = g4.parse_frontmatter(path)
    assert err is None, err

    monkeypatch.setattr(g4.core, "HAVE_YAML", False)
    stdlib_data, err = g4.parse_frontmatter(path)
    assert err is None, err

    assert pyyaml_data["title"] == stdlib_data["title"]
    assert pyyaml_data["description"] == stdlib_data["description"]
    assert pyyaml_data["title"] == "Report#42: uses C:/Users/x and a 'quoted' phrase"


def test_model_actor_entrypoint_naming_unknown_container_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["actors"][0]["entrypoint"] = "does-not-exist"
    errors = g4.validate_model(model, dset)
    assert any("does-not-exist" in e for e in errors)


def test_container_view_matches_golden(tmp_path):
    for name in ("single-container", "multi-container"):
        design_dir, model_path, expected = case(name)
        out = tmp_path / name
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        written = (out / "diagrams" / "DIA-002-container-view.md").read_text()
        golden = open(os.path.join(expected, "DIA-002-container-view.md")).read()
        assert written == golden, name


def test_intra_container_edges_are_not_container_level(tmp_path):
    """CMP-001 -> IF-001 -> CMP-002 lives entirely inside `app`; drawing it
    between containers would assert a boundary crossing that does not exist."""
    design_dir, model_path, _ = case("single-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-002-container-view.md").read_text()
    assert "IF-001" not in body
    assert "IF-002" in body  # app -> the external gateway still crosses


def test_cross_container_edge_is_drawn(tmp_path):
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-002-container-view.md").read_text()
    assert "Rel(ctr_worker, ctr_app," in body
    assert "IF-001" in body


def test_model_container_without_a_key_is_rejected():
    design_dir, model_path, _ = case("single-container")
    dset = g4.DesignSet.load(design_dir)
    model = load_model(model_path)
    model["containers"].append({
        "name": "Nameless", "technology": "Python",
        "description": "…", "components": [],
    })
    errors = g4.validate_model(model, dset)
    assert any("no 'key'" in e for e in errors)


def test_component_views_match_golden(tmp_path):
    for name, files in (
        ("single-container", ["DIA-003-component-view-order-app.md"]),
        ("multi-container", ["DIA-003-component-view-order-app.md",
                             "DIA-004-component-view-worker.md"]),
    ):
        design_dir, model_path, expected = case(name)
        out = tmp_path / name
        shutil.copytree(design_dir, out)
        g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
        for filename in files:
            written = (out / "diagrams" / filename).read_text()
            golden = open(os.path.join(expected, filename)).read()
            assert written == golden, filename


def test_cross_container_endpoint_renders_as_a_container(tmp_path):
    """The worker's edge lands on a component in another container. Drawing
    that component here would place it in two component views at once, which
    validate_design.py rejects — so it renders as the container instead."""
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    body = (out / "diagrams" / "DIA-004-component-view-worker.md").read_text()
    assert "Container(ctr_app," in body
    assert "Component(cmp_002," not in body


def test_back_fill_maps_components_to_the_view_they_appear_in(tmp_path, capsys):
    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    g4.main([str(out), "--model", model_path, "--created-at", "2026-08-22"])
    summary = json.loads(capsys.readouterr().out)
    back_fill = summary["traces_to_diagrams"]
    assert back_fill["CMP-001"] == ["DIA-003"]
    assert back_fill["CMP-004"] == ["DIA-004"]
    # An external appears at context and container level, never in a component view.
    assert back_fill["CMP-003"] == ["DIA-001", "DIA-002"]


def test_generated_set_passes_the_structural_validator(tmp_path):
    """The gate this whole feature has to survive: everything the generator
    writes is a valid artifact, consistent with the set it was drawn from."""
    import validate_design as vd

    design_dir, model_path, _ = case("multi-container")
    out = tmp_path / "design"
    shutil.copytree(design_dir, out)
    assert g4.main([str(out), "--model", model_path,
                    "--created-at", "2026-08-22"]) == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0


def test_context_view_dedupes_when_several_internals_share_an_external_edge():
    """Found against the tamagotchi worked example (STO-101 Task 10): five
    internal components (CMP-001, CMP-003, CMP-004, CMP-007, CMP-009) all
    depend on IF-001, provided by the external System Clock. At context
    level every one of those collapses to the same fact -- "the system
    depends on the clock" -- but `render_context` had no dedup, unlike
    `render_container` and `render_component`, so it emitted the identical
    `Rel(sys, ext_cmp_011, ...)` line once per consumer. No shipped fixture
    had two internal components sharing one external interface, so nothing
    caught it until a real design set did. This pins the fix: one Rel per
    distinct (source, destination, interface) triple, however many internal
    components share it."""
    dset = g4.DesignSet(
        components={
            "CMP-001": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "A", "responsibility": "…"},
            "CMP-002": {"boundary": "internal", "depends_on": ["IF-001"],
                       "title": "B", "responsibility": "…"},
            "CMP-003": {"boundary": "external", "depends_on": [],
                       "title": "Clock", "responsibility": "…"},
        },
        interfaces={
            "IF-001": {"provider": "CMP-003", "title": "Time Source"},
        },
        asrs=[],
    )
    model = {
        "system_name": "Sys",
        "system_description": "…",
        "actors": [],
        "containers": [{"key": "app", "name": "App", "technology": "…",
                        "description": "…",
                        "components": ["CMP-001", "CMP-002"]}],
    }
    block = g4.render_context(model, dset)
    assert block.count("Rel(sys, ext_cmp_003,") == 1


def test_worked_example_generates_a_valid_diagram_set(tmp_path):
    """The shipped tamagotchi set: 9 internal components, 2 external, one
    container. Pinned because it is the only real set this tool is exercised
    against, and STO-219 will regenerate it."""
    import validate_design as vd

    repo_root = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
    example = os.path.join(repo_root, "docs", "requirements", "examples",
                           "tamagotchi", "design")
    out = tmp_path / "design"
    shutil.copytree(example, out)
    shutil.rmtree(out / "diagrams")
    model = os.path.join(FIXTURES, "tamagotchi-model.json")
    assert g4.main([str(out), "--model", model, "--created-at", "2026-08-22"]) == 0
    assert vd.main([str(out), "--schema", vd.default_schema_path()]) == 0
    for name in ("DIA-001-system-context.md", "DIA-002-container-view.md",
                 "DIA-003-component-view-desktop-app.md"):
        assert (out / "diagrams" / name).exists()
