#!/usr/bin/env python3
"""Structural validator for Groundwork atomic design artifacts.

Groundwork's M2 design stage emits one atomic artifact per Markdown file with
YAML frontmatter, organized under a design directory::

    .sdlc/design/
      components/    CMP-XXX-*.md
      interfaces/    IF-XXX-*.md
      adr/           ADR-XXX-*.md
      diagrams/      DIA-XXX-*.md   (C4 views, generated by generate_c4.py)
      assumptions.md                (gated: Assumptions/Dependencies/Open Questions)
      drivers.md                    (gated: ASRs/Tradeoffs/Sensitivity Points)
      index.yaml                    (skipped)

This tool:
  1. Discovers every ``*.md`` under the design dir (recursively), skipping the
     ``assumptions.md``/``drivers.md``/``index.yaml`` companions.
  2. Parses the YAML frontmatter from each file.
  3. Validates each artifact against the JSON Schema
     (``skills/design/schema/design.schema.json``, draft 2020-12).
  4. Runs cross-file (set-level) checks:
       - IDs are globally unique.
       - The ID prefix matches ``type`` (CMP->component, IF->interface,
         ADR->adr, DIA->diagram).
       - ``depends_on`` resolves: every interface a component consumes exists
         in this set.
       - ``provider`` resolves: every interface's provider is a known component
         in this set.
       - ``traces_from`` entries are requirement-SHAPED (FR/NFR/CON/BR/UC…);
         their existence in .sdlc/requirements/ is the cross-artifact
         validator's job (STO-102), not this one.
  5. Gates the project-level ``assumptions.md`` and ``drivers.md`` (presence +
     required headings).
  6. Gates each ADR body's MADR 4.0 headings.
  7. Prints a readable per-file + summary report and exits non-zero on any
     violation.

The stage-agnostic machinery (frontmatter parsing, stdlib fallback, schema
validation, project-artifact gating, discovery, reporting) is shared with the
M1 requirements validator via ``lib/artifact_core.py``. Only the
design-specific cross-file checks and fallback field lists live here.

Usage
-----
    python3 validate_design.py [DESIGN_DIR]
    python3 validate_design.py                 # defaults to .sdlc/design
    python3 validate_design.py path/to/design
    python3 validate_design.py --schema path/to/design.schema.json design
    python3 validate_design.py --quiet design  # only print failures + summary

Exit codes
----------
    0  all files valid
    1  one or more validation errors
    2  usage / environment error (e.g. dir or schema missing)

Dependencies
------------
Full validation requires ``pyyaml`` and ``jsonschema``. Without them the tool
falls back to a minimal stdlib parser and a best-effort, per-type structural
check (never as strict as the schema path); it prints a hint to install them.
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from typing import Any, Dict, List, Optional, Set, Tuple

# Shared core lives at the repo root in ``lib/``; add it to the path before
# importing. Resolved relative to this file, so cwd does not matter.
_REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
)
_LIB_DIR = os.path.join(_REPO_ROOT, "lib")
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)

import artifact_core as core  # noqa: E402
from artifact_core import (  # noqa: E402  (re-exported for tests)
    ArtifactFile,
    extract_frontmatter_block,
    parse_frontmatter,
)


# Whole subtrees another stage owns in a non-artifact format. Empty as of
# STO-101: diagrams/ holds DIA- artifacts and is discovered like adr/.
SKIP_DIRNAMES: set = set()
# Companions that live in the design dir but are not atomic artifacts.
SKIP_FILENAMES = {"assumptions.md", "drivers.md", "index.yaml"}

# ID prefix -> expected `type`. Mirrors the schema contract.
PREFIX_TO_TYPE = {
    "CMP": "component",
    "IF": "interface",
    "ADR": "adr",
    "DIA": "diagram",
}

# Project-level assumptions artifact (design analogue of M1's context artifact).
# Design does NOT get its own glossary — it inherits requirements/glossary.md
# (STO-197 A.2), and this validator never reaches into the requirements set.
ASSUMPTIONS_ARTIFACT = "assumptions.md"
REQUIRED_ASSUMPTIONS_HEADINGS = ["## Assumptions", "## Dependencies", "## Open Questions"]

# Project-level drivers artifact (STO-99). Persists the orchestrator's ASR
# analysis alongside the tradeoffs and sensitivity points the critic produces,
# so the reasoning behind the decomposition survives the conversation that
# produced it (design spec A.6).
DRIVERS_ARTIFACT = "drivers.md"
REQUIRED_DRIVERS_HEADINGS = [
    "## Architecturally Significant Requirements",
    "## Tradeoffs",
    "## Sensitivity Points",
]

# MADR 4.0 body headings, gated per ADR file (STO-100). Presence only —
# content is never gated, exactly as for assumptions.md and drivers.md.
# `### Consequences` is H3 by MADR convention: it sits under Decision Outcome.
REQUIRED_ADR_HEADINGS = [
    "## Context and Problem Statement",
    "## Decision Drivers",
    "## Considered Options",
    "## Decision Outcome",
    "### Consequences",
]

# traces_from points at requirement IDs. We check the SHAPE only; resolution is
# STO-102's job. This mirrors the requirement schema's id pattern.
REQUIREMENT_ID_RE = re.compile(r"^(FR|NFR|CON|BR|UC)(-[A-Z0-9]+)*-[0-9]{3,}$")

# Minimal per-type required/enum knowledge for the stdlib fallback path only.
# The JSON Schema is the single source of truth when jsonschema is available;
# unevaluatedProperties composition cannot be reproduced here, hence the flat
# per-type lists (design.schema.json C.4 knock-on).
_FALLBACK_REQUIRED_BASE = [
    "id", "type", "title", "description", "traces_from", "traces_to",
    "status", "confidence", "created_at",
]
_FALLBACK_REQUIRED_BY_TYPE = {
    "component": ["responsibility", "boundary", "depends_on"],
    # `interaction` is per-operation as of STO-216; checked by
    # `_fallback_check_operations`, not by this flat list.
    "interface": ["provider", "operations", "error_modes"],
    # `chosen_option`/`considered_options` are conditional on decision_status,
    # which this path cannot express — the schema is the source of truth.
    "adr": ["decision_status"],
    # `container` is conditional on level, likewise not expressible here.
    "diagram": ["level"],
}
_FALLBACK_ENUMS = {
    "type": {"component", "interface", "adr", "diagram"},
    "boundary": {"internal", "external"},
    "confidence": {"high", "medium", "low"},
    "status": {"draft", "reviewed", "approved", "implemented", "verified", "obsolete"},
    "decision_status": {
        "proposed", "rejected", "accepted", "deprecated", "superseded",
    },
    "level": {"context", "container", "component"},
    "scope": {"project", "epic", "story"},
}

# Per-operation interaction enum (STO-216). Kept separate from _FALLBACK_ENUMS
# because that dict only scans top-level keys.
_FALLBACK_OPERATION_INTERACTIONS = {"synchronous", "asynchronous"}

# STO-216 migration hint, shared verbatim by both validation paths. On the
# fallback path this is the only signal a migrating user gets. On the schema
# path it is not: a stale contract-level `interaction` just falls out as one
# more name in `unevaluatedProperties`' "were unexpected" list, indistinguishable
# from a typo, and the interface branch's failed `then` also drags `provider`,
# `operations` and `error_modes` into that same list even though all three are
# mandatory on a real interface. `validate()` appends this message on the
# schema path too so the move has a name there as well.
RETIRED_INTERACTION_MIGRATION_MSG = (
    "'interaction' is declared per operation, not on the contract — move it "
    "into each entry of 'operations' (STO-216)"
)


class DesignFile(ArtifactFile):
    """A parsed design artifact. ``design_id`` reads the generic ``artifact_id``."""

    def __init__(self, path: str) -> None:
        super().__init__(path)
        # Populated for `type: diagram` only, by check_diagram_body (STO-101).
        self.diagram_aliases: Set[str] = set()
        self.diagram_interface_refs: Set[str] = set()

    @property
    def design_id(self) -> Optional[str]:
        return self.artifact_id

    @property
    def artifact_type(self) -> Optional[str]:
        if isinstance(self.frontmatter, dict):
            value = self.frontmatter.get("type")
            if isinstance(value, str):
                return value
        return None


# ---------------------------------------------------------------------------
# Schema validation (fallback path — design-specific, per-type field knowledge)
# ---------------------------------------------------------------------------
def _fallback_check_operations(data: Dict[str, Any]) -> List[str]:
    """Per-operation `interaction` checks for the stdlib path (STO-216).

    Interface-only: called only when `type == "interface"`, because `operations`
    itself is an interface-only field. The retired contract-level `interaction`
    check used to live here too, but that check is not type-specific — a
    top-level `interaction` is invalid on every artifact type, not just an
    interface — so it is hoisted out to `_fallback_validate` and applies to
    components and ADRs as well.
    """
    errors: List[str] = []
    operations = data.get("operations")
    if not isinstance(operations, list):
        if "operations" in data and data["operations"] not in (None, ""):
            errors.append(
                "schema(fallback): 'operations' must be a list, got "
                f"{type(data['operations']).__name__}"
            )
        return errors  # presence is the required-field check's business; shape is ours
    for index, operation in enumerate(operations):
        if not isinstance(operation, dict):
            errors.append(f"schema(fallback): operations[{index}] must be a mapping")
            continue
        name = operation.get("name", "?")
        value = operation.get("interaction")
        if value in (None, ""):
            errors.append(
                f"schema(fallback): operations[{index}] ('{name}') missing "
                "required field 'interaction'"
            )
        elif not isinstance(value, str) or value not in _FALLBACK_OPERATION_INTERACTIONS:
            errors.append(
                f"schema(fallback): operations[{index}] ('{name}') "
                f"'interaction'='{value}' not in "
                f"{sorted(_FALLBACK_OPERATION_INTERACTIONS)}"
            )
    return errors


def _fallback_validate(data: Dict[str, Any]) -> List[str]:
    """Best-effort structural validation when jsonschema is unavailable.

    Required-field presence is per-type because the schema's branch is not
    reproducible without jsonschema's unevaluatedProperties support.
    """
    errors: List[str] = []
    required = list(_FALLBACK_REQUIRED_BASE)
    branch = _FALLBACK_REQUIRED_BY_TYPE.get(data.get("type"))
    if branch:
        required.extend(branch)
    for field in required:
        if field not in data or data[field] in (None, ""):
            errors.append(f"schema(fallback): missing required field '{field}'")
    for field, allowed in _FALLBACK_ENUMS.items():
        if field in data and data[field] is not None and data[field] not in allowed:
            errors.append(
                f"schema(fallback): '{field}'='{data[field]}' not in {sorted(allowed)}"
            )
    # A retired contract-level `interaction` is invalid on every artifact type,
    # not only an interface — it has no type gate on purpose (STO-216 Deferred
    # Item). Before STO-216 the flat `_FALLBACK_ENUMS` scan caught this on a
    # component too; a type-gated check would silently stop catching it there.
    if "interaction" in data:
        errors.append(f"schema(fallback): {RETIRED_INTERACTION_MIGRATION_MSG}")
    if data.get("type") == "interface":
        errors.extend(_fallback_check_operations(data))
    tt = data.get("traces_to")
    if tt is not None and not isinstance(tt, dict):
        errors.append("schema(fallback): 'traces_to' must be a mapping")
    tf = data.get("traces_from")
    if tf is not None and not isinstance(tf, list):
        errors.append("schema(fallback): 'traces_from' must be a list")
    return errors


# ---------------------------------------------------------------------------
# Cross-file checks
# ---------------------------------------------------------------------------
def cross_file_checks(files: List[DesignFile]) -> List[str]:
    """Run set-level checks. Appends per-file errors and returns global errors."""
    global_errors: List[str] = []

    parsed = [f for f in files if isinstance(f.frontmatter, dict)]

    # Unique IDs, and the by-type id sets the graph checks resolve against.
    seen: Dict[str, str] = {}
    component_ids = set()
    interface_ids = set()
    component_boundaries: Dict[str, str] = {}
    for f in parsed:
        did = f.design_id
        if not did:
            continue
        if did in seen:
            f.errors.append(
                f"duplicate id '{did}' (also defined in {os.path.basename(seen[did])})"
            )
        else:
            seen[did] = f.path
        if f.artifact_type == "component":
            component_ids.add(did)
            boundary = f.frontmatter.get("boundary")
            if isinstance(boundary, str):
                component_boundaries[did] = boundary
        elif f.artifact_type == "interface":
            interface_ids.add(did)

    for f in parsed:
        fm = f.frontmatter
        assert fm is not None
        did = f.design_id
        dtype = fm.get("type")

        # Prefix <-> type agreement.
        if did:
            prefix = did.split("-", 1)[0]
            expected = PREFIX_TO_TYPE.get(prefix)
            if expected is None:
                f.errors.append(
                    f"id prefix '{prefix}' is not one of {sorted(PREFIX_TO_TYPE)}"
                )
            elif dtype is not None and expected != dtype:
                f.errors.append(
                    f"id prefix '{prefix}' implies type '{expected}', "
                    f"but type is '{dtype}'"
                )

        # depends_on resolves to a known interface (CMP -> IF edge).
        depends_on = fm.get("depends_on")
        if isinstance(depends_on, list):
            for target in depends_on:
                if isinstance(target, str) and target not in interface_ids:
                    f.errors.append(
                        f"dangling depends_on -> '{target}' is not a known interface id"
                    )

        # provider resolves to a known component (IF -> CMP edge).
        provider = fm.get("provider")
        if isinstance(provider, str) and provider not in component_ids:
            f.errors.append(
                f"dangling provider -> '{provider}' is not a known component id"
            )

        # traces_from is checked for requirement-shape only (STO-102 resolves).
        traces_from = fm.get("traces_from")
        if isinstance(traces_from, list):
            for target in traces_from:
                if isinstance(target, str) and not REQUIREMENT_ID_RE.match(target):
                    f.errors.append(
                        f"traces_from -> '{target}' is not a requirement-shaped id "
                        f"(expected FR/NFR/CON/BR/UC-###)"
                    )

        # ADR invariant (D5a / D1): an accepted decision's chosen_option must
        # be one of its own considered_options. agents/adr-generator.md
        # asserts this but nothing previously enforced it.
        chosen_option = fm.get("chosen_option")
        considered_options = fm.get("considered_options")
        if (
            chosen_option is not None
            and isinstance(considered_options, list)
            and chosen_option not in considered_options
        ):
            f.errors.append(
                f"chosen_option '{chosen_option}' is not in considered_options "
                f"{considered_options}"
            )

    # Diagram <-> artifact-set consistency (STO-101). The check STO-102's
    # description named and could not ship, because there were no diagrams.
    depicted_by_view: Dict[str, List[str]] = {}
    has_component_view = False
    for f in parsed:
        if f.artifact_type != "diagram":
            continue
        if f.frontmatter.get("level") == "component":
            has_component_view = True
        for alias in sorted(f.diagram_aliases):
            cmp_id, is_external = component_id_for_alias(alias)
            if cmp_id is None:
                continue  # containers, actors, the system box: not artifacts
            if cmp_id not in component_ids:
                f.errors.append(
                    f"alias '{alias}' depicts '{cmp_id}', which is not a "
                    f"known component id"
                )
                continue
            actual = component_boundaries.get(cmp_id)
            expected = "external" if is_external else "internal"
            if actual is not None and actual != expected:
                f.errors.append(
                    f"alias '{alias}' declares boundary '{expected}' but "
                    f"{cmp_id} is '{actual}'"
                )
            if f.frontmatter.get("level") == "component" and not is_external:
                depicted_by_view.setdefault(cmp_id, []).append(f.design_id or "?")
        for ref in sorted(f.diagram_interface_refs):
            if ref not in interface_ids:
                f.errors.append(
                    f"relation cites '{ref}', which is not a known interface id"
                )

    if has_component_view:
        for cmp_id in sorted(component_ids):
            if component_boundaries.get(cmp_id) != "internal":
                continue
            views = depicted_by_view.get(cmp_id, [])
            if not views:
                global_errors.append(
                    f"{cmp_id} appears in no component-level diagram"
                )
            elif len(views) > 1:
                global_errors.append(
                    f"{cmp_id} appears in {len(views)} component-level "
                    f"diagrams ({', '.join(sorted(views))}) — a component "
                    f"belongs to exactly one container"
                )

    return global_errors


def check_assumptions_artifact(design_dir: str) -> List[str]:
    """Assumptions/Dependencies/Open-Questions artifact (hard gate).

    The design analogue of M1's context artifact, gated by the shared core.
    An honest 'None identified' section is legal — content is never gated.
    """
    return core._check_project_artifact(
        design_dir,
        ASSUMPTIONS_ARTIFACT,
        REQUIRED_ASSUMPTIONS_HEADINGS,
        "assumptions artifact",
        "Assumptions / Dependencies / Open Questions",
    )


def check_drivers_artifact(design_dir: str) -> List[str]:
    """Architectural-drivers artifact (hard gate).

    Presence plus the three headings, gated by the shared core. As with the
    assumptions artifact, content is never gated — an honest 'None identified'
    section is legal and passes.
    """
    return core._check_project_artifact(
        design_dir,
        DRIVERS_ARTIFACT,
        REQUIRED_DRIVERS_HEADINGS,
        "drivers artifact",
        "Architecturally Significant Requirements / Tradeoffs / Sensitivity Points",
    )


def check_adr_headings(path: str) -> List[str]:
    """Gate one ADR body's MADR 4.0 headings.

    Presence only; content is never gated. Unlike assumptions.md and drivers.md
    this is per-file rather than per-directory, so it does not go through
    ``core._check_project_artifact`` (which resolves a fixed filename inside a
    root). The heading-anchoring regex is the same: a full-line match, so an
    H3 '### Considered Options' does not satisfy the H2 requirement.
    """
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError) as exc:
        return [f"could not read ADR body: {exc}"]

    errors: List[str] = []
    for heading in REQUIRED_ADR_HEADINGS:
        if not re.search(rf"^{re.escape(heading)}\s*$", text, re.MULTILINE):
            errors.append(f"missing required MADR heading '{heading}'")
    return errors


# Mermaid C4 body checks (STO-101). The header directive each `level` must
# open with — a file that disagrees with itself is two claims about one
# diagram.
LEVEL_TO_HEADER = {
    "context": "C4Context",
    "container": "C4Container",
    "component": "C4Component",
}

_MERMAID_BLOCK_RE = re.compile(
    r"^```mermaid\s*\n(.*?)^```\s*$", re.DOTALL | re.MULTILINE
)

# Element declarations introduce an alias; relations consume one. Both are
# `Keyword(alias, ...)`, so one regex with a keyword group serves both.
_DECL_RE = re.compile(
    r"^\s*(Person|Person_Ext|System|System_Ext|System_Boundary|Container"
    r"|Container_Ext|Container_Boundary|Component|Component_Ext)"
    r"\(\s*([A-Za-z0-9_]+)\s*,"
)
_REL_RE = re.compile(
    r"^\s*(?:Rel|BiRel|Rel_Back|Rel_U|Rel_D|Rel_L|Rel_R|Rel_Up|Rel_Down"
    r"|Rel_Left|Rel_Right)"
    r"\(\s*([A-Za-z0-9_]+)\s*,\s*([A-Za-z0-9_]+)\s*[,)]"
)
_INTERFACE_REF_RE = re.compile(r"\b(IF(?:-[A-Z0-9]+)*-[0-9]{3,})\b")

# Reverse of the generator's alias rule (spec D4): strip the external marker,
# upper-case, swap underscores back to hyphens. Total and reversible, which is
# what lets the validator map any node in a body back to the artifact it
# claims to depict — no `depicts` frontmatter field, and so no second copy of
# the mapping to drift.
_COMPONENT_ALIAS_RE = re.compile(r"^(ext_)?(cmp(?:_[a-z0-9]+)*_[0-9]{3,})$")


def component_id_for_alias(alias):
    """``('CMP-001', is_external)`` for a component alias, else ``(None, False)``."""
    match = _COMPONENT_ALIAS_RE.match(alias)
    if not match:
        return None, False
    return match.group(2).upper().replace("_", "-"), bool(match.group(1))


def check_diagram_body(
    path: str, level: Optional[str]
) -> Tuple[List[str], Set[str], Set[str]]:
    """Gate one diagram body's Mermaid block.

    Returns ``(errors, declared_aliases, interface_refs)``. The last two are
    what ``cross_file_checks`` resolves against the artifact set — parsed here
    because this is the only pass that reads the body.
    """
    errors = []
    try:
        with open(path, "r", encoding="utf-8") as handle:
            text = handle.read()
    except (OSError, UnicodeDecodeError) as exc:
        return [f"could not read diagram body: {exc}"], set(), set()

    blocks = _MERMAID_BLOCK_RE.findall(text)
    if not blocks:
        return ["body has no ```mermaid block"], set(), set()
    if len(blocks) > 1:
        errors.append(
            f"body has {len(blocks)} ```mermaid blocks — one diagram per file"
        )
    block = blocks[0]

    lines = [ln for ln in block.splitlines() if ln.strip()]
    expected_header = LEVEL_TO_HEADER.get(level) if level else None
    header = lines[0].strip() if lines else ""
    if expected_header and header != expected_header:
        errors.append(
            f"level '{level}' requires header '{expected_header}', "
            f"but the block opens with '{header or '(empty)'}'"
        )

    declared = set()
    refs = set()
    endpoints = []
    for line in lines:
        if line.count("(") != line.count(")") or line.count('"') % 2:
            errors.append(f"unbalanced quotes or parentheses: {line.strip()}")
            continue
        decl = _DECL_RE.match(line)
        if decl:
            declared.add(decl.group(2))
        rel = _REL_RE.match(line)
        if rel:
            endpoints.extend([rel.group(1), rel.group(2)])
            refs.update(_INTERFACE_REF_RE.findall(line))

    for alias in sorted(set(endpoints)):
        if alias not in declared:
            errors.append(
                f"relation endpoint '{alias}' is not declared in this diagram"
            )

    return errors, declared, refs


# ---------------------------------------------------------------------------
# Discovery + orchestration
# ---------------------------------------------------------------------------
def discover_files(design_dir: str) -> List[str]:
    """Every design artifact ``*.md`` under ``design_dir`` (companions/subtrees skipped)."""
    return core.discover_files(design_dir, SKIP_FILENAMES, SKIP_DIRNAMES)


def validate(design_dir: str, schema_path: str) -> Tuple[List[DesignFile], List[str]]:
    files: List[DesignFile] = []

    validator = core.make_validator(schema_path)

    for path in discover_files(design_dir):
        df = DesignFile(path)
        data, err = parse_frontmatter(path)
        if err:
            df.errors.append(err)
            files.append(df)
            continue
        df.frontmatter = data
        if validator is not None:
            df.errors.extend(core.validate_against_schema(data, validator))
            # A retired contract-level `interaction` on an interface fails the
            # branch `then`, so none of the branch's own properties get
            # evaluated and `unevaluatedProperties` reports `provider`,
            # `operations` and `error_modes` — all three mandatory on a real
            # interface — as unexpected right alongside it (schema $comment
            # "Diagnostic note"). The schema still does the rejecting; this
            # only adds the same named hint the fallback path already gives,
            # so a migrating user is told what actually moved.
            if data.get("type") == "interface" and "interaction" in data:
                df.errors.append(f"schema: (root): {RETIRED_INTERACTION_MIGRATION_MSG}")
        else:
            df.errors.extend(_fallback_validate(data))
        if data.get("type") == "adr":
            df.errors.extend(check_adr_headings(path))
        if data.get("type") == "diagram":
            body_errors, aliases, refs = check_diagram_body(path, data.get("level"))
            df.errors.extend(body_errors)
            df.diagram_aliases = aliases
            df.diagram_interface_refs = refs
        files.append(df)

    global_errors = cross_file_checks(files)
    global_errors.extend(check_assumptions_artifact(design_dir))
    global_errors.extend(check_drivers_artifact(design_dir))
    return files, global_errors


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def default_schema_path() -> str:
    # schema lives at ../schema/design.schema.json relative to this script.
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "schema", "design.schema.json"))


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Validate Groundwork atomic design artifacts."
    )
    parser.add_argument(
        "design_dir",
        nargs="?",
        default=".sdlc/design",
        help="Directory of design files (default: .sdlc/design).",
    )
    parser.add_argument(
        "--schema",
        default=None,
        help="Path to design.schema.json (default: alongside this script).",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Only print failures and the summary line.",
    )
    args = parser.parse_args(argv)

    design_dir = args.design_dir
    schema_path = args.schema or default_schema_path()

    if not os.path.isdir(design_dir):
        print(f"ERROR: design directory not found: {design_dir}", file=sys.stderr)
        return 2
    if core.HAVE_JSONSCHEMA and not os.path.isfile(schema_path):
        print(f"ERROR: schema file not found: {schema_path}", file=sys.stderr)
        return 2

    files, global_errors = validate(design_dir, schema_path)
    core.print_report(files, global_errors, design_dir, args.quiet, noun="design artifact")

    has_errors = bool(global_errors) or any(not f.ok for f in files)
    return 1 if has_errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
