#!/usr/bin/env python3
"""Deterministic Definition of Done generation for Groundwork (STO-104).

Every gate this tool emits is already stated somewhere in the artifact set: a
frontmatter field, or one of two fixed sections in an NFR body. So the DoD is a
projection of what the pipeline wrote, not a new authored document — the same
argument ``generate_c4.py`` makes for the C4 views, and the reason this
replaced the M1 ``dod-generator`` agent.

The output is written to ``.sdlc/definition-of-done.md``: root level, under no
stage directory, because the DoD is the one artifact no single stage owns. All
three stage skills run this tool and each run supersedes the last, so a project
that only ever runs ``/groundwork:requirements`` still gets a Definition of
Done — that is what the root path buys.

Sections appear exactly when their inputs do. A stage that was not run is
absent from the document and named as absent in the header, rather than
rendering an empty heading that reads as "nothing to do here".

Usage
-----
    python3 generate_dod.py --requirements DIR [--design DIR] [--qa DIR] \\
        --out .sdlc/definition-of-done.md [--title NAME] [--created-at DATE]

Exit codes
----------
    0  document written
    1  an artifact this tool must parse is malformed
    2  usage / environment error (no stage given, directory missing)
"""
from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
from typing import Any, Dict, List, Optional

_REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
)
_LIB_DIR = os.path.join(_REPO_ROOT, "lib")
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)

import artifact_core as core  # noqa: E402
from artifact_core import parse_frontmatter  # noqa: E402

# Project-level companions that live beside atomic artifacts but are not ones.
SKIP_REQUIREMENTS = {
    "definition-of-done.md", "index.yaml", "assumptions.md", "glossary.md",
}
SKIP_DESIGN = {"index.yaml", "assumptions.md", "drivers.md"}
SKIP_QA = {"index.yaml", "qa-strategy.md"}
SKIP_DESIGN_DIRS = {"diagrams"}

GENERATED_BANNER = (
    "<!-- Generated by generate_dod.py. Do not hand-edit: change the source "
    "artifact under .sdlc/ and regenerate. -->"
)


class Artifact:
    """One parsed artifact: its frontmatter and its Markdown body."""

    __slots__ = ("path", "fm", "body")

    def __init__(self, path: str, fm: Dict[str, Any], body: str) -> None:
        self.path = path
        self.fm = fm
        self.body = body

    @property
    def id(self) -> Optional[str]:
        value = self.fm.get("id")
        return value if isinstance(value, str) else None

    @property
    def type(self) -> Optional[str]:
        value = self.fm.get("type")
        return value if isinstance(value, str) else None

    def get(self, key: str, default: Any = None) -> Any:
        return self.fm.get(key, default)


class GenerationError(Exception):
    """An artifact this tool must parse is malformed. Maps to exit 1."""


def _read_body(path: str) -> str:
    """Everything after the closing frontmatter fence."""
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    block = core.extract_frontmatter_block(text)
    if block is None:
        return text
    fence_end = text.index(block) + len(block)
    remainder = text[fence_end:]
    return remainder.split("---", 1)[1] if "---" in remainder else remainder


# ---------------------------------------------------------------------------
# NFR body parsing
#
# Two sections of an NFR body are load-bearing here. Both are written by
# nfr-specialist.md for every NFR and are present in all 24 NFRs across both
# worked example sets; validate_requirements.py gates them so that a drift in
# the specialist's template fails at the validator rather than here.
# ---------------------------------------------------------------------------
ISO_HEADING = "## ISO 25010 Characteristic"

# The nine ISO/IEC 25010:2023 characteristics nfr-specialist.md walks, plus the
# "Extension:" prefix it uses for the four the standard omits (observability,
# deployability, compliance, cost). Only the head token is parsed: the text
# after the separator is free prose that wraps and carries parentheticals, so
# Extension: Observability and Extension: Compliance land in one bucket. That
# is deliberate — see spec D8.
ISO_CHARACTERISTICS = frozenset({
    "Functional Suitability",
    "Performance Efficiency",
    "Compatibility",
    "Interaction Capability",
    "Reliability",
    "Security",
    "Maintainability",
    "Flexibility",
    "Safety",
    "Extension",
})

_ISO_SECTION_RE = re.compile(
    r"^## ISO 25010 Characteristic\s*\n(.+?)(?=^##\s|\Z)", re.M | re.S
)
_QAS_SEPARATOR_RE = re.compile(r"→|->|:")


def parse_iso_characteristic(artifact: Artifact) -> str:
    """The head token of an NFR's ``## ISO 25010 Characteristic`` section."""
    match = _ISO_SECTION_RE.search(artifact.body)
    if not match:
        raise GenerationError(
            f"{artifact.id}: missing required heading '{ISO_HEADING}'"
        )
    text = " ".join(match.group(1).split())
    head = _QAS_SEPARATOR_RE.split(text, 1)[0].strip()
    if head not in ISO_CHARACTERISTICS:
        raise GenerationError(
            f"{artifact.id}: '{head}' is not an ISO 25010 characteristic or "
            f"an 'Extension'"
        )
    return head


def parse_qas_field(artifact: Artifact, label: str) -> str:
    """One six-part quality-attribute-scenario bullet, continuations joined.

    A bullet ends at the next bullet or the next heading, so a value wrapped
    across lines (which the specialist does routinely) survives intact.
    """
    pattern = re.compile(
        r"^-\s+\*\*" + re.escape(label) + r":\*\*\s*(.+?)(?=^-\s+\*\*|^#{1,6}\s|\Z)",
        re.M | re.S,
    )
    match = pattern.search(artifact.body)
    if not match:
        raise GenerationError(
            f"{artifact.id}: quality attribute scenario has no "
            f"'**{label}:**' bullet"
        )
    return " ".join(match.group(1).split())


def load_set(root: str, skip: set, skip_dirs: set = frozenset()) -> List[Artifact]:
    """Every atomic artifact under ``root``, sorted by id.

    Raises GenerationError on unparseable frontmatter rather than skipping the
    file: a DoD that silently omits a requirement is claiming coverage it does
    not have, which is the failure mode this tool exists to prevent.
    """
    artifacts: List[Artifact] = []
    for path in core.discover_files(root, skip, skip_dirs):
        data, err = parse_frontmatter(path)
        if err:
            raise GenerationError(f"{os.path.relpath(path, root)}: {err}")
        artifacts.append(Artifact(path, data, _read_body(path)))
    return sorted(artifacts, key=lambda a: a.id or "")


def _stage_marker(present: bool) -> str:
    return "✓" if present else "—"


# ---------------------------------------------------------------------------
# Gate rendering
# ---------------------------------------------------------------------------
def by_type(artifacts: Optional[List[Artifact]], *types: str) -> List[Artifact]:
    if not artifacts:
        return []
    return [a for a in artifacts if a.type in types]


def coverage_map(qa: Optional[List[Artifact]]) -> Dict[str, List[Artifact]]:
    """requirement/design id -> the TS items whose traces_from cites it."""
    out: Dict[str, List[Artifact]] = {}
    for item in by_type(qa, "test_strategy"):
        for target in item.get("traces_from") or []:
            out.setdefault(str(target), []).append(item)
    return out


def enforcement_tag(
    req: Artifact, covering: List[Artifact], qa_present: bool
) -> str:
    """How strongly this requirement's gate is actually checked.

    With a QA set on disk the answer is derived from the items covering it.
    Without one there is nothing to derive from, so the tag reports the
    requirement's own verification_method instead of claiming a pipeline.
    """
    if not qa_present:
        return f"`[verification: {req.get('verification_method', 'unspecified')}]`"
    if not covering:
        return "`[uncovered]`"
    levels = {str(item.get("enforcement")) for item in covering}
    if "ci" in levels:
        return "`[CI]`"
    if "manual" in levels:
        return "`[manual]`"
    return "`[unenforced]`"


def _rel_source(artifact: Artifact, root: str, stage_dir: str) -> str:
    return f"`{stage_dir}/{os.path.relpath(artifact.path, root)}`"


def render_functional_gates(
    reqs: List[Artifact], root: str, coverage: Dict[str, List[Artifact]],
    qa_present: bool,
) -> List[str]:
    items = by_type(reqs, "functional")
    if not items:
        return []
    lines = [
        "## Functional Acceptance Gates",
        "",
        "One gate per functional requirement. The linked file holds the "
        "authoritative acceptance criteria; they are referenced here, never "
        "duplicated.",
        "",
    ]
    for req in items:
        tag = enforcement_tag(req, coverage.get(req.id or "", []), qa_present)
        lines += [
            f"- [ ] **{req.id} — {req.get('title')}** "
            f"({req.get('priority')}) {tag}",
            "  All acceptance-criteria scenarios in the source file pass.",
            f"  Fit criterion: {req.get('fit_criterion')}",
            f"  Source: {_rel_source(req, root, '.sdlc/requirements')}",
            "",
        ]
    return lines


def render_nfr_gates(
    reqs: List[Artifact], root: str, coverage: Dict[str, List[Artifact]],
    qa_present: bool,
) -> List[str]:
    items = by_type(reqs, "non_functional")
    if not items:
        return []
    lines = [
        "## NFR Fitness Gates",
        "",
        "The quality attribute scenario's response measure is the pass/fail "
        "oracle for each gate below.",
        "",
    ]
    for req in items:
        tag = enforcement_tag(req, coverage.get(req.id or "", []), qa_present)
        measure = parse_qas_field(req, "Response measure")
        stimulus = parse_qas_field(req, "Stimulus")
        artifact_under_test = parse_qas_field(req, "Artifact")
        environment = parse_qas_field(req, "Environment")
        lines += [
            f"- [ ] **{req.id} — {req.get('title')}** "
            f"({req.get('priority')}) {tag}",
            f"  Response measure: {measure}",
            f"  Scenario: *{stimulus}* on *{artifact_under_test}* "
            f"under *{environment}*.",
            f"  Source: {_rel_source(req, root, '.sdlc/requirements')}",
            "",
        ]
    return lines


def render_conformance_gates(design: List[Artifact], root: str) -> List[str]:
    """Accepted decisions and declared dependency edges.

    Not "fitness functions": design.schema.json carries no threshold, target or
    measure anywhere. A fitness function has a measure; these have a rule. The
    measurable architecture gates are the NFR fitness gates above.
    """
    adrs = [
        a for a in by_type(design, "adr")
        if a.get("decision_status") == "accepted"
    ]
    components = [
        c for c in by_type(design, "component") if c.get("depends_on")
    ]
    if not adrs and not components:
        return []
    lines = [
        "## Architectural Conformance Gates",
        "",
        "Decisions the implementation must not quietly reverse, and the "
        "dependency edges the design declared.",
        "",
    ]
    for adr in adrs:
        lines += [
            f"- [ ] **{adr.id} — {adr.get('title')}** `[manual]`",
            f"  The implementation conforms to the chosen option: "
            f"{adr.get('chosen_option')}",
            f"  Source: {_rel_source(adr, root, '.sdlc/design')}",
            "",
        ]
    for cmp_ in components:
        edges = ", ".join(str(d) for d in cmp_.get("depends_on") or [])
        lines += [
            f"- [ ] **{cmp_.id} — {cmp_.get('title')}** `[manual]`",
            f"  Depends on nothing outside its declared interfaces: {edges}.",
            f"  Source: {_rel_source(cmp_, root, '.sdlc/design')}",
            "",
        ]
    return lines


def render_coverage(
    reqs: List[Artifact], coverage: Dict[str, List[Artifact]], root: str
) -> List[str]:
    """Which test-strategy items cite each requirement.

    Derivation, not enforcement. validate_traceability.py's uncovered-fr and
    uncovered-asr rules own the gate over this same edge; rendering it here
    twice would put the rule in two places.
    """
    items = by_type(reqs, "functional", "non_functional", "constraint", "business_rule")
    if not items:
        return []
    lines = [
        "## Test Coverage",
        "",
        "Derived from each test-strategy item's `traces_from`. A requirement "
        "no item cites is a gap, not a pass.",
        "",
    ]
    for req in items:
        covering = coverage.get(req.id or "", [])
        if covering:
            described = ", ".join(
                f"{item.id} ({item.get('test_level')}, {item.get('enforcement')})"
                for item in sorted(covering, key=lambda a: a.id or "")
            )
            lines.append(f"- [ ] **{req.id}** — covered by {described}")
        else:
            lines.append(
                f"- [ ] **{req.id}** — **no test-strategy item cites this "
                f"requirement**"
            )
    lines.append("")
    return lines


def render_unenforced(qa: List[Artifact], root: str) -> List[str]:
    """Items that declared themselves unenforced.

    A DoD that lists every gate but drops the items marked `enforcement: none`
    is claiming coverage the project does not have. Not a checklist: there is
    nothing here for anyone to tick.
    """
    items = [
        a for a in by_type(qa, "test_strategy") if a.get("enforcement") == "none"
    ]
    if not items:
        return []
    lines = [
        "## Declared Unenforced",
        "",
        "Test strategy the project decided not to enforce. Recorded so the "
        "coverage claimed above is not read as coverage delivered.",
        "",
    ]
    for item in items:
        covers = ", ".join(str(t) for t in item.get("traces_from") or [])
        lines += [
            f"- **{item.id} — {item.get('title')}** "
            f"(`{item.get('test_level')}`, risk: {item.get('risk_level')})",
            f"  Rationale: {item.get('risk_rationale')}",
            f"  Covers: {covers}. Source: {_rel_source(item, root, '.sdlc/qa')}",
            "",
        ]
    return lines


# ---------------------------------------------------------------------------
# Documentation + deployment readiness (spec D4)
# ---------------------------------------------------------------------------
# Characteristics whose NFRs need runbook or configuration notes. "Extension"
# is taken wholesale: only the head token is parsed, so Observability,
# Deployability, Compliance and Cost share one bucket (spec D8).
DOC_CHARACTERISTICS = ("Security", "Reliability", "Extension")


def nfrs_by_characteristic(reqs: List[Artifact]) -> Dict[str, List[Artifact]]:
    out: Dict[str, List[Artifact]] = {}
    for req in by_type(reqs, "non_functional"):
        out.setdefault(parse_iso_characteristic(req), []).append(req)
    return out


def _id_list(artifacts: List[Artifact]) -> str:
    if not artifacts:
        return "none"
    return ", ".join(str(a.id) for a in artifacts)


def _chars(by_char: Dict[str, List[Artifact]], names) -> List[str]:
    parts: List[str] = []
    for name in names:
        for req in by_char.get(name, []):
            parts.append(f"{req.id} ({name})")
    return parts


def render_documentation(
    reqs: List[Artifact], by_char: Dict[str, List[Artifact]]
) -> List[str]:
    must_frs = [r for r in by_type(reqs, "functional") if r.get("priority") == "must"]
    operational = _chars(by_char, DOC_CHARACTERISTICS)
    return [
        "## Documentation Requirements",
        "",
        f"- [ ] Public-facing behaviour of every `must` functional requirement "
        f"is documented: {_id_list(must_frs)}.",
        f"- [ ] Operational NFRs have runbook or configuration notes: "
        f"{', '.join(operational) if operational else 'none'}.",
        "- [ ] Every implemented artifact carries `status: implemented` (or "
        "`verified`) and a populated `traces_to.code`.",
        "",
    ]


def render_deployment(
    reqs: List[Artifact], by_char: Dict[str, List[Artifact]]
) -> List[str]:
    security = by_char.get("Security", [])
    reliability = by_char.get("Reliability", [])
    rules = by_type(reqs, "constraint", "business_rule")
    return [
        "## Deployment / Operational Readiness",
        "",
        f"- [ ] Security NFR gates pass before release: {_id_list(security)}.",
        f"- [ ] Reliability targets are met or have an accepted waiver: "
        f"{_id_list(reliability)}.",
        "- [ ] Observability is in place for the response measures asserted "
        "above.",
        f"- [ ] Constraints and business rules hold in the deployed "
        f"configuration: {_id_list(rules)}.",
        "",
    ]


def render_document(
    reqs: Optional[List[Artifact]],
    design: Optional[List[Artifact]],
    qa: Optional[List[Artifact]],
    title: Optional[str],
    today: str,
    roots: Dict[str, str],
) -> str:
    lines: List[str] = ["# Definition of Done", "", GENERATED_BANNER, ""]
    if title:
        lines.append(f"- **Project / feature:** {title}")
    lines.append(f"- **Generated:** {today}")
    lines.append(
        "- **Derived from:** "
        f"requirements {_stage_marker(reqs is not None)} · "
        f"design {_stage_marker(design is not None)} · "
        f"qa {_stage_marker(qa is not None)}"
    )
    lines += [
        "",
        "A work item is **Done** only when every gate below is satisfied.",
        "",
    ]
    coverage = coverage_map(qa)
    qa_present = qa is not None
    body: List[str] = []
    if reqs:
        body += render_functional_gates(
            reqs, roots["requirements"], coverage, qa_present
        )
        body += render_nfr_gates(reqs, roots["requirements"], coverage, qa_present)
    if design:
        body += render_conformance_gates(design, roots["design"])
    if qa:
        if reqs:
            body += render_coverage(reqs, coverage, roots["requirements"])
        body += render_unenforced(qa, roots["qa"])
    if reqs:
        by_char = nfrs_by_characteristic(reqs)
        body += render_documentation(reqs, by_char)
        body += render_deployment(reqs, by_char)
    lines += body
    lines += [
        "---",
        "",
        "*Generated from the artifact sets under `.sdlc/`. Change the source "
        "artifact and regenerate; do not edit this file.*",
    ]
    return "\n".join(lines) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Definition of Done from Groundwork artifact sets."
    )
    parser.add_argument("--requirements", default=None, help="Requirements dir.")
    parser.add_argument("--design", default=None, help="Design dir (optional).")
    parser.add_argument("--qa", default=None, help="QA dir (optional).")
    parser.add_argument("--out", required=True, help="Output path.")
    parser.add_argument("--title", default=None, help="Project or feature name.")
    parser.add_argument("--created-at", default=None, help="Override today's date.")
    args = parser.parse_args(argv)

    stages = {
        "requirements": args.requirements,
        "design": args.design,
        "qa": args.qa,
    }
    if not any(stages.values()):
        print(
            "ERROR: name at least one artifact directory "
            "(--requirements / --design / --qa)",
            file=sys.stderr,
        )
        return 2
    for name, path in stages.items():
        if path is not None and not os.path.isdir(path):
            print(f"ERROR: {name} directory not found: {path}", file=sys.stderr)
            return 2

    roots = {k: v for k, v in stages.items() if v}
    today = args.created_at or datetime.date.today().isoformat()

    try:
        reqs = load_set(args.requirements, SKIP_REQUIREMENTS) if args.requirements else None
        design = (
            load_set(args.design, SKIP_DESIGN, SKIP_DESIGN_DIRS) if args.design else None
        )
        qa = load_set(args.qa, SKIP_QA) if args.qa else None
        document = render_document(reqs, design, qa, args.title, today, roots)
    except GenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(document)
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
