#!/usr/bin/env python3
"""Deterministic Definition of Done generation for Groundwork (STO-104).

Every gate this tool emits is already stated somewhere in the artifact set: a
frontmatter field, or one of two fixed sections in an NFR body. So the DoD is a
projection of what the pipeline wrote, not a new authored document — the same
argument ``generate_c4.py`` makes for the C4 views, and the reason this
replaced the M1 ``dod-generator`` agent.

The output is written to ``.sdlc/definition-of-done.md``: root level, under no
stage directory, because the DoD is the one artifact no single stage owns. All
three stage skills run this tool and each run supersedes the last, so a project
that only ever runs ``/groundwork:requirements`` still gets a Definition of
Done — that is what the root path buys.

Sections appear exactly when their inputs do. A stage that was not run is
absent from the document and named as absent in the header, rather than
rendering an empty heading that reads as "nothing to do here".

Usage
-----
    python3 generate_dod.py --requirements DIR [--design DIR] [--qa DIR] \\
        --out .sdlc/definition-of-done.md [--title NAME] [--created-at DATE]

Exit codes
----------
    0  document written
    1  an artifact this tool must parse is malformed
    2  usage / environment error (no stage given, directory missing)
"""
from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
from typing import Any, Dict, List, Optional

_REPO_ROOT = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..")
)
_LIB_DIR = os.path.join(_REPO_ROOT, "lib")
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)

import artifact_core as core  # noqa: E402
from artifact_core import parse_frontmatter  # noqa: E402

# Project-level companions that live beside atomic artifacts but are not ones.
SKIP_REQUIREMENTS = {
    "definition-of-done.md", "index.yaml", "assumptions.md", "glossary.md",
}
SKIP_DESIGN = {"index.yaml", "assumptions.md", "drivers.md"}
SKIP_QA = {"index.yaml", "qa-strategy.md"}
SKIP_DESIGN_DIRS = {"diagrams"}

GENERATED_BANNER = (
    "<!-- Generated by generate_dod.py. Do not hand-edit: change the source "
    "artifact under .sdlc/ and regenerate. -->"
)


class Artifact:
    """One parsed artifact: its frontmatter and its Markdown body."""

    __slots__ = ("path", "fm", "body")

    def __init__(self, path: str, fm: Dict[str, Any], body: str) -> None:
        self.path = path
        self.fm = fm
        self.body = body

    @property
    def id(self) -> Optional[str]:
        value = self.fm.get("id")
        return value if isinstance(value, str) else None

    @property
    def type(self) -> Optional[str]:
        value = self.fm.get("type")
        return value if isinstance(value, str) else None

    def get(self, key: str, default: Any = None) -> Any:
        return self.fm.get(key, default)


class GenerationError(Exception):
    """An artifact this tool must parse is malformed. Maps to exit 1."""


def _read_body(path: str) -> str:
    """Everything after the closing frontmatter fence."""
    with open(path, "r", encoding="utf-8") as handle:
        text = handle.read()
    block = core.extract_frontmatter_block(text)
    if block is None:
        return text
    fence_end = text.index(block) + len(block)
    remainder = text[fence_end:]
    return remainder.split("---", 1)[1] if "---" in remainder else remainder


def load_set(root: str, skip: set, skip_dirs: set = frozenset()) -> List[Artifact]:
    """Every atomic artifact under ``root``, sorted by id.

    Raises GenerationError on unparseable frontmatter rather than skipping the
    file: a DoD that silently omits a requirement is claiming coverage it does
    not have, which is the failure mode this tool exists to prevent.
    """
    artifacts: List[Artifact] = []
    for path in core.discover_files(root, skip, skip_dirs):
        data, err = parse_frontmatter(path)
        if err:
            raise GenerationError(f"{os.path.relpath(path, root)}: {err}")
        artifacts.append(Artifact(path, data, _read_body(path)))
    return sorted(artifacts, key=lambda a: a.id or "")


def _stage_marker(present: bool) -> str:
    return "✓" if present else "—"


def render_document(
    reqs: Optional[List[Artifact]],
    design: Optional[List[Artifact]],
    qa: Optional[List[Artifact]],
    title: Optional[str],
    today: str,
) -> str:
    lines: List[str] = ["# Definition of Done", "", GENERATED_BANNER, ""]
    if title:
        lines.append(f"- **Project / feature:** {title}")
    lines.append(f"- **Generated:** {today}")
    lines.append(
        "- **Derived from:** "
        f"requirements {_stage_marker(reqs is not None)} · "
        f"design {_stage_marker(design is not None)} · "
        f"qa {_stage_marker(qa is not None)}"
    )
    lines += [
        "",
        "A work item is **Done** only when every gate below is satisfied.",
        "",
    ]
    lines += [
        "---",
        "",
        "*Generated from the artifact sets under `.sdlc/`. Change the source "
        "artifact and regenerate; do not edit this file.*",
    ]
    return "\n".join(lines) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate a Definition of Done from Groundwork artifact sets."
    )
    parser.add_argument("--requirements", default=None, help="Requirements dir.")
    parser.add_argument("--design", default=None, help="Design dir (optional).")
    parser.add_argument("--qa", default=None, help="QA dir (optional).")
    parser.add_argument("--out", required=True, help="Output path.")
    parser.add_argument("--title", default=None, help="Project or feature name.")
    parser.add_argument("--created-at", default=None, help="Override today's date.")
    args = parser.parse_args(argv)

    stages = {
        "requirements": args.requirements,
        "design": args.design,
        "qa": args.qa,
    }
    if not any(stages.values()):
        print(
            "ERROR: name at least one artifact directory "
            "(--requirements / --design / --qa)",
            file=sys.stderr,
        )
        return 2
    for name, path in stages.items():
        if path is not None and not os.path.isdir(path):
            print(f"ERROR: {name} directory not found: {path}", file=sys.stderr)
            return 2

    try:
        reqs = load_set(args.requirements, SKIP_REQUIREMENTS) if args.requirements else None
        design = (
            load_set(args.design, SKIP_DESIGN, SKIP_DESIGN_DIRS) if args.design else None
        )
        qa = load_set(args.qa, SKIP_QA) if args.qa else None
    except GenerationError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    today = args.created_at or datetime.date.today().isoformat()
    document = render_document(reqs, design, qa, args.title, today)

    out_dir = os.path.dirname(os.path.abspath(args.out))
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(document)
    print(f"Wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
